services:
  - type: web
    name: maharashtra-sports
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server-node.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
