/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as StipendsGrantsRouteImport } from './routes/stipends-grants'
import { Route as StadiumsArenasRouteImport } from './routes/stadiums-arenas'
import { Route as SportsComplexesRouteImport } from './routes/sports-complexes'
import { Route as SportsAcademiesRouteImport } from './routes/sports-academies'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ResultsArchiveRouteImport } from './routes/results-archive'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrganisationStructureRouteImport } from './routes/organisation-structure'
import { Route as OlympiansRouteImport } from './routes/olympians'
import { Route as NationalGamesRouteImport } from './routes/national-games'
import { Route as MediaCenterRouteImport } from './routes/media-center'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveScoresRouteImport } from './routes/live-scores'
import { Route as LeadershipTeamRouteImport } from './routes/leadership-team'
import { Route as InfrastructureMapRouteImport } from './routes/infrastructure-map'
import { Route as HostelSchemesRouteImport } from './routes/hostel-schemes'
import { Route as EventCalendarRouteImport } from './routes/event-calendar'
import { Route as EliteAthletesRouteImport } from './routes/elite-athletes'
import { Route as DistrictWebsitesRouteImport } from './routes/district-websites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AwardSchemesRouteImport } from './routes/award-schemes'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StadiumsArenasIndexRouteImport } from './routes/stadiums-arenas.index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as OlympiansIndexRouteImport } from './routes/olympians.index'
import { Route as MediaCenterIndexRouteImport } from './routes/media-center.index'
import { Route as DistrictWebsitesIndexRouteImport } from './routes/district-websites.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as StadiumsArenasIdRouteImport } from './routes/stadiums-arenas.$id'
import { Route as RegisterYouthClubRouteImport } from './routes/register.youth-club'
import { Route as RegisterSportsComplexRouteImport } from './routes/register.sports-complex'
import { Route as RegisterLocalSelfGovernmentRouteImport } from './routes/register.local-self-government'
import { Route as RegisterInstitutionRouteImport } from './routes/register.institution'
import { Route as RegisterDepartmentOfficerRouteImport } from './routes/register.department-officer'
import { Route as RegisterAthleteCoachRouteImport } from './routes/register.athlete-coach'
import { Route as RegisterAssociationRouteImport } from './routes/register.association'
import { Route as OlympiansIdRouteImport } from './routes/olympians.$id'
import { Route as NoticesRecruitmentsRouteImport } from './routes/notices.recruitments'
import { Route as NoticesPastEventsRouteImport } from './routes/notices.past-events'
import { Route as NoticesETendersRouteImport } from './routes/notices.e-tenders'
import { Route as NoticesAnnouncementsRouteImport } from './routes/notices.announcements'
import { Route as MediaCenterVideoGalleryRouteImport } from './routes/media-center.video-gallery'
import { Route as MediaCenterPressReleasesRouteImport } from './routes/media-center.press-releases'
import { Route as MediaCenterPhotoGalleryRouteImport } from './routes/media-center.photo-gallery'
import { Route as MediaCenterNewsRouteImport } from './routes/media-center.news'
import { Route as EliteAthletesIdRouteImport } from './routes/elite-athletes.$id'
import { Route as DistrictWebsitesIdRouteImport } from './routes/district-websites.$id'
import { Route as DashboardScholarshipRouteImport } from './routes/dashboard.scholarship'
import { Route as DashboardGrievanceRouteImport } from './routes/dashboard.grievance'
import { Route as DashboardFundUtilizationRouteImport } from './routes/dashboard.fund-utilization'
import { Route as DashboardCmRouteImport } from './routes/dashboard.cm'
import { Route as OlympiansIdIndexRouteImport } from './routes/olympians.$id.index'
import { Route as OlympiansIdHighlightsRouteImport } from './routes/olympians.$id.highlights'
import { Route as MediaCenterVideoGalleryIdRouteImport } from './routes/media-center.video-gallery.$id'
import { Route as MediaCenterPressReleasesIdRouteImport } from './routes/media-center.press-releases.$id'
import { Route as MediaCenterPhotoGalleryIdRouteImport } from './routes/media-center.photo-gallery.$id'
import { Route as MediaCenterNewsIdRouteImport } from './routes/media-center.news.$id'

const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const StipendsGrantsRoute = StipendsGrantsRouteImport.update({
  id: '/stipends-grants',
  path: '/stipends-grants',
  getParentRoute: () => rootRouteImport,
} as any)
const StadiumsArenasRoute = StadiumsArenasRouteImport.update({
  id: '/stadiums-arenas',
  path: '/stadiums-arenas',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsComplexesRoute = SportsComplexesRouteImport.update({
  id: '/sports-complexes',
  path: '/sports-complexes',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsAcademiesRoute = SportsAcademiesRouteImport.update({
  id: '/sports-academies',
  path: '/sports-academies',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsArchiveRoute = ResultsArchiveRouteImport.update({
  id: '/results-archive',
  path: '/results-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationStructureRoute = OrganisationStructureRouteImport.update({
  id: '/organisation-structure',
  path: '/organisation-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const OlympiansRoute = OlympiansRouteImport.update({
  id: '/olympians',
  path: '/olympians',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalGamesRoute = NationalGamesRouteImport.update({
  id: '/national-games',
  path: '/national-games',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCenterRoute = MediaCenterRouteImport.update({
  id: '/media-center',
  path: '/media-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveScoresRoute = LiveScoresRouteImport.update({
  id: '/live-scores',
  path: '/live-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipTeamRoute = LeadershipTeamRouteImport.update({
  id: '/leadership-team',
  path: '/leadership-team',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureMapRoute = InfrastructureMapRouteImport.update({
  id: '/infrastructure-map',
  path: '/infrastructure-map',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelSchemesRoute = HostelSchemesRouteImport.update({
  id: '/hostel-schemes',
  path: '/hostel-schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventCalendarRoute = EventCalendarRouteImport.update({
  id: '/event-calendar',
  path: '/event-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const EliteAthletesRoute = EliteAthletesRouteImport.update({
  id: '/elite-athletes',
  path: '/elite-athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictWebsitesRoute = DistrictWebsitesRouteImport.update({
  id: '/district-websites',
  path: '/district-websites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardSchemesRoute = AwardSchemesRouteImport.update({
  id: '/award-schemes',
  path: '/award-schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StadiumsArenasIndexRoute = StadiumsArenasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StadiumsArenasRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const OlympiansIndexRoute = OlympiansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OlympiansRoute,
} as any)
const MediaCenterIndexRoute = MediaCenterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaCenterRoute,
} as any)
const DistrictWebsitesIndexRoute = DistrictWebsitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DistrictWebsitesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const StadiumsArenasIdRoute = StadiumsArenasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StadiumsArenasRoute,
} as any)
const RegisterYouthClubRoute = RegisterYouthClubRouteImport.update({
  id: '/youth-club',
  path: '/youth-club',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterSportsComplexRoute = RegisterSportsComplexRouteImport.update({
  id: '/sports-complex',
  path: '/sports-complex',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterLocalSelfGovernmentRoute =
  RegisterLocalSelfGovernmentRouteImport.update({
    id: '/local-self-government',
    path: '/local-self-government',
    getParentRoute: () => RegisterRoute,
  } as any)
const RegisterInstitutionRoute = RegisterInstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterDepartmentOfficerRoute =
  RegisterDepartmentOfficerRouteImport.update({
    id: '/department-officer',
    path: '/department-officer',
    getParentRoute: () => RegisterRoute,
  } as any)
const RegisterAthleteCoachRoute = RegisterAthleteCoachRouteImport.update({
  id: '/athlete-coach',
  path: '/athlete-coach',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterAssociationRoute = RegisterAssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => RegisterRoute,
} as any)
const OlympiansIdRoute = OlympiansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OlympiansRoute,
} as any)
const NoticesRecruitmentsRoute = NoticesRecruitmentsRouteImport.update({
  id: '/notices/recruitments',
  path: '/notices/recruitments',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesPastEventsRoute = NoticesPastEventsRouteImport.update({
  id: '/notices/past-events',
  path: '/notices/past-events',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesETendersRoute = NoticesETendersRouteImport.update({
  id: '/notices/e-tenders',
  path: '/notices/e-tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesAnnouncementsRoute = NoticesAnnouncementsRouteImport.update({
  id: '/notices/announcements',
  path: '/notices/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaCenterVideoGalleryRoute = MediaCenterVideoGalleryRouteImport.update({
  id: '/video-gallery',
  path: '/video-gallery',
  getParentRoute: () => MediaCenterRoute,
} as any)
const MediaCenterPressReleasesRoute =
  MediaCenterPressReleasesRouteImport.update({
    id: '/press-releases',
    path: '/press-releases',
    getParentRoute: () => MediaCenterRoute,
  } as any)
const MediaCenterPhotoGalleryRoute = MediaCenterPhotoGalleryRouteImport.update({
  id: '/photo-gallery',
  path: '/photo-gallery',
  getParentRoute: () => MediaCenterRoute,
} as any)
const MediaCenterNewsRoute = MediaCenterNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => MediaCenterRoute,
} as any)
const EliteAthletesIdRoute = EliteAthletesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EliteAthletesRoute,
} as any)
const DistrictWebsitesIdRoute = DistrictWebsitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DistrictWebsitesRoute,
} as any)
const DashboardScholarshipRoute = DashboardScholarshipRouteImport.update({
  id: '/scholarship',
  path: '/scholarship',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGrievanceRoute = DashboardGrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFundUtilizationRoute =
  DashboardFundUtilizationRouteImport.update({
    id: '/fund-utilization',
    path: '/fund-utilization',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCmRoute = DashboardCmRouteImport.update({
  id: '/cm',
  path: '/cm',
  getParentRoute: () => DashboardRoute,
} as any)
const OlympiansIdIndexRoute = OlympiansIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OlympiansIdRoute,
} as any)
const OlympiansIdHighlightsRoute = OlympiansIdHighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => OlympiansIdRoute,
} as any)
const MediaCenterVideoGalleryIdRoute =
  MediaCenterVideoGalleryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => MediaCenterVideoGalleryRoute,
  } as any)
const MediaCenterPressReleasesIdRoute =
  MediaCenterPressReleasesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => MediaCenterPressReleasesRoute,
  } as any)
const MediaCenterPhotoGalleryIdRoute =
  MediaCenterPhotoGalleryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => MediaCenterPhotoGalleryRoute,
  } as any)
const MediaCenterNewsIdRoute = MediaCenterNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MediaCenterNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/award-schemes': typeof AwardSchemesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/district-websites': typeof DistrictWebsitesRouteWithChildren
  '/elite-athletes': typeof EliteAthletesRouteWithChildren
  '/event-calendar': typeof EventCalendarRoute
  '/hostel-schemes': typeof HostelSchemesRoute
  '/infrastructure-map': typeof InfrastructureMapRoute
  '/leadership-team': typeof LeadershipTeamRoute
  '/live-scores': typeof LiveScoresRoute
  '/login': typeof LoginRoute
  '/media-center': typeof MediaCenterRouteWithChildren
  '/national-games': typeof NationalGamesRoute
  '/olympians': typeof OlympiansRouteWithChildren
  '/organisation-structure': typeof OrganisationStructureRoute
  '/register': typeof RegisterRouteWithChildren
  '/results-archive': typeof ResultsArchiveRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sports-academies': typeof SportsAcademiesRoute
  '/sports-complexes': typeof SportsComplexesRoute
  '/stadiums-arenas': typeof StadiumsArenasRouteWithChildren
  '/stipends-grants': typeof StipendsGrantsRoute
  '/venues': typeof VenuesRoute
  '/dashboard/cm': typeof DashboardCmRoute
  '/dashboard/fund-utilization': typeof DashboardFundUtilizationRoute
  '/dashboard/grievance': typeof DashboardGrievanceRoute
  '/dashboard/scholarship': typeof DashboardScholarshipRoute
  '/district-websites/$id': typeof DistrictWebsitesIdRoute
  '/elite-athletes/$id': typeof EliteAthletesIdRoute
  '/media-center/news': typeof MediaCenterNewsRouteWithChildren
  '/media-center/photo-gallery': typeof MediaCenterPhotoGalleryRouteWithChildren
  '/media-center/press-releases': typeof MediaCenterPressReleasesRouteWithChildren
  '/media-center/video-gallery': typeof MediaCenterVideoGalleryRouteWithChildren
  '/notices/announcements': typeof NoticesAnnouncementsRoute
  '/notices/e-tenders': typeof NoticesETendersRoute
  '/notices/past-events': typeof NoticesPastEventsRoute
  '/notices/recruitments': typeof NoticesRecruitmentsRoute
  '/olympians/$id': typeof OlympiansIdRouteWithChildren
  '/register/association': typeof RegisterAssociationRoute
  '/register/athlete-coach': typeof RegisterAthleteCoachRoute
  '/register/department-officer': typeof RegisterDepartmentOfficerRoute
  '/register/institution': typeof RegisterInstitutionRoute
  '/register/local-self-government': typeof RegisterLocalSelfGovernmentRoute
  '/register/sports-complex': typeof RegisterSportsComplexRoute
  '/register/youth-club': typeof RegisterYouthClubRoute
  '/stadiums-arenas/$id': typeof StadiumsArenasIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/district-websites/': typeof DistrictWebsitesIndexRoute
  '/media-center/': typeof MediaCenterIndexRoute
  '/olympians/': typeof OlympiansIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/stadiums-arenas/': typeof StadiumsArenasIndexRoute
  '/media-center/news/$id': typeof MediaCenterNewsIdRoute
  '/media-center/photo-gallery/$id': typeof MediaCenterPhotoGalleryIdRoute
  '/media-center/press-releases/$id': typeof MediaCenterPressReleasesIdRoute
  '/media-center/video-gallery/$id': typeof MediaCenterVideoGalleryIdRoute
  '/olympians/$id/highlights': typeof OlympiansIdHighlightsRoute
  '/olympians/$id/': typeof OlympiansIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/award-schemes': typeof AwardSchemesRoute
  '/elite-athletes': typeof EliteAthletesRouteWithChildren
  '/event-calendar': typeof EventCalendarRoute
  '/hostel-schemes': typeof HostelSchemesRoute
  '/infrastructure-map': typeof InfrastructureMapRoute
  '/leadership-team': typeof LeadershipTeamRoute
  '/live-scores': typeof LiveScoresRoute
  '/login': typeof LoginRoute
  '/national-games': typeof NationalGamesRoute
  '/organisation-structure': typeof OrganisationStructureRoute
  '/results-archive': typeof ResultsArchiveRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sports-academies': typeof SportsAcademiesRoute
  '/sports-complexes': typeof SportsComplexesRoute
  '/stipends-grants': typeof StipendsGrantsRoute
  '/venues': typeof VenuesRoute
  '/dashboard/cm': typeof DashboardCmRoute
  '/dashboard/fund-utilization': typeof DashboardFundUtilizationRoute
  '/dashboard/grievance': typeof DashboardGrievanceRoute
  '/dashboard/scholarship': typeof DashboardScholarshipRoute
  '/district-websites/$id': typeof DistrictWebsitesIdRoute
  '/elite-athletes/$id': typeof EliteAthletesIdRoute
  '/media-center/news': typeof MediaCenterNewsRouteWithChildren
  '/media-center/photo-gallery': typeof MediaCenterPhotoGalleryRouteWithChildren
  '/media-center/press-releases': typeof MediaCenterPressReleasesRouteWithChildren
  '/media-center/video-gallery': typeof MediaCenterVideoGalleryRouteWithChildren
  '/notices/announcements': typeof NoticesAnnouncementsRoute
  '/notices/e-tenders': typeof NoticesETendersRoute
  '/notices/past-events': typeof NoticesPastEventsRoute
  '/notices/recruitments': typeof NoticesRecruitmentsRoute
  '/register/association': typeof RegisterAssociationRoute
  '/register/athlete-coach': typeof RegisterAthleteCoachRoute
  '/register/department-officer': typeof RegisterDepartmentOfficerRoute
  '/register/institution': typeof RegisterInstitutionRoute
  '/register/local-self-government': typeof RegisterLocalSelfGovernmentRoute
  '/register/sports-complex': typeof RegisterSportsComplexRoute
  '/register/youth-club': typeof RegisterYouthClubRoute
  '/stadiums-arenas/$id': typeof StadiumsArenasIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/district-websites': typeof DistrictWebsitesIndexRoute
  '/media-center': typeof MediaCenterIndexRoute
  '/olympians': typeof OlympiansIndexRoute
  '/register': typeof RegisterIndexRoute
  '/stadiums-arenas': typeof StadiumsArenasIndexRoute
  '/media-center/news/$id': typeof MediaCenterNewsIdRoute
  '/media-center/photo-gallery/$id': typeof MediaCenterPhotoGalleryIdRoute
  '/media-center/press-releases/$id': typeof MediaCenterPressReleasesIdRoute
  '/media-center/video-gallery/$id': typeof MediaCenterVideoGalleryIdRoute
  '/olympians/$id/highlights': typeof OlympiansIdHighlightsRoute
  '/olympians/$id': typeof OlympiansIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/award-schemes': typeof AwardSchemesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/district-websites': typeof DistrictWebsitesRouteWithChildren
  '/elite-athletes': typeof EliteAthletesRouteWithChildren
  '/event-calendar': typeof EventCalendarRoute
  '/hostel-schemes': typeof HostelSchemesRoute
  '/infrastructure-map': typeof InfrastructureMapRoute
  '/leadership-team': typeof LeadershipTeamRoute
  '/live-scores': typeof LiveScoresRoute
  '/login': typeof LoginRoute
  '/media-center': typeof MediaCenterRouteWithChildren
  '/national-games': typeof NationalGamesRoute
  '/olympians': typeof OlympiansRouteWithChildren
  '/organisation-structure': typeof OrganisationStructureRoute
  '/register': typeof RegisterRouteWithChildren
  '/results-archive': typeof ResultsArchiveRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sports-academies': typeof SportsAcademiesRoute
  '/sports-complexes': typeof SportsComplexesRoute
  '/stadiums-arenas': typeof StadiumsArenasRouteWithChildren
  '/stipends-grants': typeof StipendsGrantsRoute
  '/venues': typeof VenuesRoute
  '/dashboard/cm': typeof DashboardCmRoute
  '/dashboard/fund-utilization': typeof DashboardFundUtilizationRoute
  '/dashboard/grievance': typeof DashboardGrievanceRoute
  '/dashboard/scholarship': typeof DashboardScholarshipRoute
  '/district-websites/$id': typeof DistrictWebsitesIdRoute
  '/elite-athletes/$id': typeof EliteAthletesIdRoute
  '/media-center/news': typeof MediaCenterNewsRouteWithChildren
  '/media-center/photo-gallery': typeof MediaCenterPhotoGalleryRouteWithChildren
  '/media-center/press-releases': typeof MediaCenterPressReleasesRouteWithChildren
  '/media-center/video-gallery': typeof MediaCenterVideoGalleryRouteWithChildren
  '/notices/announcements': typeof NoticesAnnouncementsRoute
  '/notices/e-tenders': typeof NoticesETendersRoute
  '/notices/past-events': typeof NoticesPastEventsRoute
  '/notices/recruitments': typeof NoticesRecruitmentsRoute
  '/olympians/$id': typeof OlympiansIdRouteWithChildren
  '/register/association': typeof RegisterAssociationRoute
  '/register/athlete-coach': typeof RegisterAthleteCoachRoute
  '/register/department-officer': typeof RegisterDepartmentOfficerRoute
  '/register/institution': typeof RegisterInstitutionRoute
  '/register/local-self-government': typeof RegisterLocalSelfGovernmentRoute
  '/register/sports-complex': typeof RegisterSportsComplexRoute
  '/register/youth-club': typeof RegisterYouthClubRoute
  '/stadiums-arenas/$id': typeof StadiumsArenasIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/district-websites/': typeof DistrictWebsitesIndexRoute
  '/media-center/': typeof MediaCenterIndexRoute
  '/olympians/': typeof OlympiansIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/stadiums-arenas/': typeof StadiumsArenasIndexRoute
  '/media-center/news/$id': typeof MediaCenterNewsIdRoute
  '/media-center/photo-gallery/$id': typeof MediaCenterPhotoGalleryIdRoute
  '/media-center/press-releases/$id': typeof MediaCenterPressReleasesIdRoute
  '/media-center/video-gallery/$id': typeof MediaCenterVideoGalleryIdRoute
  '/olympians/$id/highlights': typeof OlympiansIdHighlightsRoute
  '/olympians/$id/': typeof OlympiansIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/award-schemes'
    | '/dashboard'
    | '/district-websites'
    | '/elite-athletes'
    | '/event-calendar'
    | '/hostel-schemes'
    | '/infrastructure-map'
    | '/leadership-team'
    | '/live-scores'
    | '/login'
    | '/media-center'
    | '/national-games'
    | '/olympians'
    | '/organisation-structure'
    | '/register'
    | '/results-archive'
    | '/scholarships'
    | '/sports-academies'
    | '/sports-complexes'
    | '/stadiums-arenas'
    | '/stipends-grants'
    | '/venues'
    | '/dashboard/cm'
    | '/dashboard/fund-utilization'
    | '/dashboard/grievance'
    | '/dashboard/scholarship'
    | '/district-websites/$id'
    | '/elite-athletes/$id'
    | '/media-center/news'
    | '/media-center/photo-gallery'
    | '/media-center/press-releases'
    | '/media-center/video-gallery'
    | '/notices/announcements'
    | '/notices/e-tenders'
    | '/notices/past-events'
    | '/notices/recruitments'
    | '/olympians/$id'
    | '/register/association'
    | '/register/athlete-coach'
    | '/register/department-officer'
    | '/register/institution'
    | '/register/local-self-government'
    | '/register/sports-complex'
    | '/register/youth-club'
    | '/stadiums-arenas/$id'
    | '/dashboard/'
    | '/district-websites/'
    | '/media-center/'
    | '/olympians/'
    | '/register/'
    | '/stadiums-arenas/'
    | '/media-center/news/$id'
    | '/media-center/photo-gallery/$id'
    | '/media-center/press-releases/$id'
    | '/media-center/video-gallery/$id'
    | '/olympians/$id/highlights'
    | '/olympians/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/award-schemes'
    | '/elite-athletes'
    | '/event-calendar'
    | '/hostel-schemes'
    | '/infrastructure-map'
    | '/leadership-team'
    | '/live-scores'
    | '/login'
    | '/national-games'
    | '/organisation-structure'
    | '/results-archive'
    | '/scholarships'
    | '/sports-academies'
    | '/sports-complexes'
    | '/stipends-grants'
    | '/venues'
    | '/dashboard/cm'
    | '/dashboard/fund-utilization'
    | '/dashboard/grievance'
    | '/dashboard/scholarship'
    | '/district-websites/$id'
    | '/elite-athletes/$id'
    | '/media-center/news'
    | '/media-center/photo-gallery'
    | '/media-center/press-releases'
    | '/media-center/video-gallery'
    | '/notices/announcements'
    | '/notices/e-tenders'
    | '/notices/past-events'
    | '/notices/recruitments'
    | '/register/association'
    | '/register/athlete-coach'
    | '/register/department-officer'
    | '/register/institution'
    | '/register/local-self-government'
    | '/register/sports-complex'
    | '/register/youth-club'
    | '/stadiums-arenas/$id'
    | '/dashboard'
    | '/district-websites'
    | '/media-center'
    | '/olympians'
    | '/register'
    | '/stadiums-arenas'
    | '/media-center/news/$id'
    | '/media-center/photo-gallery/$id'
    | '/media-center/press-releases/$id'
    | '/media-center/video-gallery/$id'
    | '/olympians/$id/highlights'
    | '/olympians/$id'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/award-schemes'
    | '/dashboard'
    | '/district-websites'
    | '/elite-athletes'
    | '/event-calendar'
    | '/hostel-schemes'
    | '/infrastructure-map'
    | '/leadership-team'
    | '/live-scores'
    | '/login'
    | '/media-center'
    | '/national-games'
    | '/olympians'
    | '/organisation-structure'
    | '/register'
    | '/results-archive'
    | '/scholarships'
    | '/sports-academies'
    | '/sports-complexes'
    | '/stadiums-arenas'
    | '/stipends-grants'
    | '/venues'
    | '/dashboard/cm'
    | '/dashboard/fund-utilization'
    | '/dashboard/grievance'
    | '/dashboard/scholarship'
    | '/district-websites/$id'
    | '/elite-athletes/$id'
    | '/media-center/news'
    | '/media-center/photo-gallery'
    | '/media-center/press-releases'
    | '/media-center/video-gallery'
    | '/notices/announcements'
    | '/notices/e-tenders'
    | '/notices/past-events'
    | '/notices/recruitments'
    | '/olympians/$id'
    | '/register/association'
    | '/register/athlete-coach'
    | '/register/department-officer'
    | '/register/institution'
    | '/register/local-self-government'
    | '/register/sports-complex'
    | '/register/youth-club'
    | '/stadiums-arenas/$id'
    | '/dashboard/'
    | '/district-websites/'
    | '/media-center/'
    | '/olympians/'
    | '/register/'
    | '/stadiums-arenas/'
    | '/media-center/news/$id'
    | '/media-center/photo-gallery/$id'
    | '/media-center/press-releases/$id'
    | '/media-center/video-gallery/$id'
    | '/olympians/$id/highlights'
    | '/olympians/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AwardSchemesRoute: typeof AwardSchemesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DistrictWebsitesRoute: typeof DistrictWebsitesRouteWithChildren
  EliteAthletesRoute: typeof EliteAthletesRouteWithChildren
  EventCalendarRoute: typeof EventCalendarRoute
  HostelSchemesRoute: typeof HostelSchemesRoute
  InfrastructureMapRoute: typeof InfrastructureMapRoute
  LeadershipTeamRoute: typeof LeadershipTeamRoute
  LiveScoresRoute: typeof LiveScoresRoute
  LoginRoute: typeof LoginRoute
  MediaCenterRoute: typeof MediaCenterRouteWithChildren
  NationalGamesRoute: typeof NationalGamesRoute
  OlympiansRoute: typeof OlympiansRouteWithChildren
  OrganisationStructureRoute: typeof OrganisationStructureRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  ResultsArchiveRoute: typeof ResultsArchiveRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SportsAcademiesRoute: typeof SportsAcademiesRoute
  SportsComplexesRoute: typeof SportsComplexesRoute
  StadiumsArenasRoute: typeof StadiumsArenasRouteWithChildren
  StipendsGrantsRoute: typeof StipendsGrantsRoute
  VenuesRoute: typeof VenuesRoute
  NoticesAnnouncementsRoute: typeof NoticesAnnouncementsRoute
  NoticesETendersRoute: typeof NoticesETendersRoute
  NoticesPastEventsRoute: typeof NoticesPastEventsRoute
  NoticesRecruitmentsRoute: typeof NoticesRecruitmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stipends-grants': {
      id: '/stipends-grants'
      path: '/stipends-grants'
      fullPath: '/stipends-grants'
      preLoaderRoute: typeof StipendsGrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadiums-arenas': {
      id: '/stadiums-arenas'
      path: '/stadiums-arenas'
      fullPath: '/stadiums-arenas'
      preLoaderRoute: typeof StadiumsArenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-complexes': {
      id: '/sports-complexes'
      path: '/sports-complexes'
      fullPath: '/sports-complexes'
      preLoaderRoute: typeof SportsComplexesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-academies': {
      id: '/sports-academies'
      path: '/sports-academies'
      fullPath: '/sports-academies'
      preLoaderRoute: typeof SportsAcademiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results-archive': {
      id: '/results-archive'
      path: '/results-archive'
      fullPath: '/results-archive'
      preLoaderRoute: typeof ResultsArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation-structure': {
      id: '/organisation-structure'
      path: '/organisation-structure'
      fullPath: '/organisation-structure'
      preLoaderRoute: typeof OrganisationStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olympians': {
      id: '/olympians'
      path: '/olympians'
      fullPath: '/olympians'
      preLoaderRoute: typeof OlympiansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national-games': {
      id: '/national-games'
      path: '/national-games'
      fullPath: '/national-games'
      preLoaderRoute: typeof NationalGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-center': {
      id: '/media-center'
      path: '/media-center'
      fullPath: '/media-center'
      preLoaderRoute: typeof MediaCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-scores': {
      id: '/live-scores'
      path: '/live-scores'
      fullPath: '/live-scores'
      preLoaderRoute: typeof LiveScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership-team': {
      id: '/leadership-team'
      path: '/leadership-team'
      fullPath: '/leadership-team'
      preLoaderRoute: typeof LeadershipTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure-map': {
      id: '/infrastructure-map'
      path: '/infrastructure-map'
      fullPath: '/infrastructure-map'
      preLoaderRoute: typeof InfrastructureMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel-schemes': {
      id: '/hostel-schemes'
      path: '/hostel-schemes'
      fullPath: '/hostel-schemes'
      preLoaderRoute: typeof HostelSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-calendar': {
      id: '/event-calendar'
      path: '/event-calendar'
      fullPath: '/event-calendar'
      preLoaderRoute: typeof EventCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite-athletes': {
      id: '/elite-athletes'
      path: '/elite-athletes'
      fullPath: '/elite-athletes'
      preLoaderRoute: typeof EliteAthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district-websites': {
      id: '/district-websites'
      path: '/district-websites'
      fullPath: '/district-websites'
      preLoaderRoute: typeof DistrictWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/award-schemes': {
      id: '/award-schemes'
      path: '/award-schemes'
      fullPath: '/award-schemes'
      preLoaderRoute: typeof AwardSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadiums-arenas/': {
      id: '/stadiums-arenas/'
      path: '/'
      fullPath: '/stadiums-arenas/'
      preLoaderRoute: typeof StadiumsArenasIndexRouteImport
      parentRoute: typeof StadiumsArenasRoute
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/olympians/': {
      id: '/olympians/'
      path: '/'
      fullPath: '/olympians/'
      preLoaderRoute: typeof OlympiansIndexRouteImport
      parentRoute: typeof OlympiansRoute
    }
    '/media-center/': {
      id: '/media-center/'
      path: '/'
      fullPath: '/media-center/'
      preLoaderRoute: typeof MediaCenterIndexRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/district-websites/': {
      id: '/district-websites/'
      path: '/'
      fullPath: '/district-websites/'
      preLoaderRoute: typeof DistrictWebsitesIndexRouteImport
      parentRoute: typeof DistrictWebsitesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/stadiums-arenas/$id': {
      id: '/stadiums-arenas/$id'
      path: '/$id'
      fullPath: '/stadiums-arenas/$id'
      preLoaderRoute: typeof StadiumsArenasIdRouteImport
      parentRoute: typeof StadiumsArenasRoute
    }
    '/register/youth-club': {
      id: '/register/youth-club'
      path: '/youth-club'
      fullPath: '/register/youth-club'
      preLoaderRoute: typeof RegisterYouthClubRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/sports-complex': {
      id: '/register/sports-complex'
      path: '/sports-complex'
      fullPath: '/register/sports-complex'
      preLoaderRoute: typeof RegisterSportsComplexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/local-self-government': {
      id: '/register/local-self-government'
      path: '/local-self-government'
      fullPath: '/register/local-self-government'
      preLoaderRoute: typeof RegisterLocalSelfGovernmentRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/institution': {
      id: '/register/institution'
      path: '/institution'
      fullPath: '/register/institution'
      preLoaderRoute: typeof RegisterInstitutionRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/department-officer': {
      id: '/register/department-officer'
      path: '/department-officer'
      fullPath: '/register/department-officer'
      preLoaderRoute: typeof RegisterDepartmentOfficerRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/athlete-coach': {
      id: '/register/athlete-coach'
      path: '/athlete-coach'
      fullPath: '/register/athlete-coach'
      preLoaderRoute: typeof RegisterAthleteCoachRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/association': {
      id: '/register/association'
      path: '/association'
      fullPath: '/register/association'
      preLoaderRoute: typeof RegisterAssociationRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/olympians/$id': {
      id: '/olympians/$id'
      path: '/$id'
      fullPath: '/olympians/$id'
      preLoaderRoute: typeof OlympiansIdRouteImport
      parentRoute: typeof OlympiansRoute
    }
    '/notices/recruitments': {
      id: '/notices/recruitments'
      path: '/notices/recruitments'
      fullPath: '/notices/recruitments'
      preLoaderRoute: typeof NoticesRecruitmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/past-events': {
      id: '/notices/past-events'
      path: '/notices/past-events'
      fullPath: '/notices/past-events'
      preLoaderRoute: typeof NoticesPastEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/e-tenders': {
      id: '/notices/e-tenders'
      path: '/notices/e-tenders'
      fullPath: '/notices/e-tenders'
      preLoaderRoute: typeof NoticesETendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/announcements': {
      id: '/notices/announcements'
      path: '/notices/announcements'
      fullPath: '/notices/announcements'
      preLoaderRoute: typeof NoticesAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-center/video-gallery': {
      id: '/media-center/video-gallery'
      path: '/video-gallery'
      fullPath: '/media-center/video-gallery'
      preLoaderRoute: typeof MediaCenterVideoGalleryRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/media-center/press-releases': {
      id: '/media-center/press-releases'
      path: '/press-releases'
      fullPath: '/media-center/press-releases'
      preLoaderRoute: typeof MediaCenterPressReleasesRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/media-center/photo-gallery': {
      id: '/media-center/photo-gallery'
      path: '/photo-gallery'
      fullPath: '/media-center/photo-gallery'
      preLoaderRoute: typeof MediaCenterPhotoGalleryRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/media-center/news': {
      id: '/media-center/news'
      path: '/news'
      fullPath: '/media-center/news'
      preLoaderRoute: typeof MediaCenterNewsRouteImport
      parentRoute: typeof MediaCenterRoute
    }
    '/elite-athletes/$id': {
      id: '/elite-athletes/$id'
      path: '/$id'
      fullPath: '/elite-athletes/$id'
      preLoaderRoute: typeof EliteAthletesIdRouteImport
      parentRoute: typeof EliteAthletesRoute
    }
    '/district-websites/$id': {
      id: '/district-websites/$id'
      path: '/$id'
      fullPath: '/district-websites/$id'
      preLoaderRoute: typeof DistrictWebsitesIdRouteImport
      parentRoute: typeof DistrictWebsitesRoute
    }
    '/dashboard/scholarship': {
      id: '/dashboard/scholarship'
      path: '/scholarship'
      fullPath: '/dashboard/scholarship'
      preLoaderRoute: typeof DashboardScholarshipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/grievance': {
      id: '/dashboard/grievance'
      path: '/grievance'
      fullPath: '/dashboard/grievance'
      preLoaderRoute: typeof DashboardGrievanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fund-utilization': {
      id: '/dashboard/fund-utilization'
      path: '/fund-utilization'
      fullPath: '/dashboard/fund-utilization'
      preLoaderRoute: typeof DashboardFundUtilizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cm': {
      id: '/dashboard/cm'
      path: '/cm'
      fullPath: '/dashboard/cm'
      preLoaderRoute: typeof DashboardCmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/olympians/$id/': {
      id: '/olympians/$id/'
      path: '/'
      fullPath: '/olympians/$id/'
      preLoaderRoute: typeof OlympiansIdIndexRouteImport
      parentRoute: typeof OlympiansIdRoute
    }
    '/olympians/$id/highlights': {
      id: '/olympians/$id/highlights'
      path: '/highlights'
      fullPath: '/olympians/$id/highlights'
      preLoaderRoute: typeof OlympiansIdHighlightsRouteImport
      parentRoute: typeof OlympiansIdRoute
    }
    '/media-center/video-gallery/$id': {
      id: '/media-center/video-gallery/$id'
      path: '/$id'
      fullPath: '/media-center/video-gallery/$id'
      preLoaderRoute: typeof MediaCenterVideoGalleryIdRouteImport
      parentRoute: typeof MediaCenterVideoGalleryRoute
    }
    '/media-center/press-releases/$id': {
      id: '/media-center/press-releases/$id'
      path: '/$id'
      fullPath: '/media-center/press-releases/$id'
      preLoaderRoute: typeof MediaCenterPressReleasesIdRouteImport
      parentRoute: typeof MediaCenterPressReleasesRoute
    }
    '/media-center/photo-gallery/$id': {
      id: '/media-center/photo-gallery/$id'
      path: '/$id'
      fullPath: '/media-center/photo-gallery/$id'
      preLoaderRoute: typeof MediaCenterPhotoGalleryIdRouteImport
      parentRoute: typeof MediaCenterPhotoGalleryRoute
    }
    '/media-center/news/$id': {
      id: '/media-center/news/$id'
      path: '/$id'
      fullPath: '/media-center/news/$id'
      preLoaderRoute: typeof MediaCenterNewsIdRouteImport
      parentRoute: typeof MediaCenterNewsRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCmRoute: typeof DashboardCmRoute
  DashboardFundUtilizationRoute: typeof DashboardFundUtilizationRoute
  DashboardGrievanceRoute: typeof DashboardGrievanceRoute
  DashboardScholarshipRoute: typeof DashboardScholarshipRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCmRoute: DashboardCmRoute,
  DashboardFundUtilizationRoute: DashboardFundUtilizationRoute,
  DashboardGrievanceRoute: DashboardGrievanceRoute,
  DashboardScholarshipRoute: DashboardScholarshipRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DistrictWebsitesRouteChildren {
  DistrictWebsitesIdRoute: typeof DistrictWebsitesIdRoute
  DistrictWebsitesIndexRoute: typeof DistrictWebsitesIndexRoute
}

const DistrictWebsitesRouteChildren: DistrictWebsitesRouteChildren = {
  DistrictWebsitesIdRoute: DistrictWebsitesIdRoute,
  DistrictWebsitesIndexRoute: DistrictWebsitesIndexRoute,
}

const DistrictWebsitesRouteWithChildren =
  DistrictWebsitesRoute._addFileChildren(DistrictWebsitesRouteChildren)

interface EliteAthletesRouteChildren {
  EliteAthletesIdRoute: typeof EliteAthletesIdRoute
}

const EliteAthletesRouteChildren: EliteAthletesRouteChildren = {
  EliteAthletesIdRoute: EliteAthletesIdRoute,
}

const EliteAthletesRouteWithChildren = EliteAthletesRoute._addFileChildren(
  EliteAthletesRouteChildren,
)

interface MediaCenterNewsRouteChildren {
  MediaCenterNewsIdRoute: typeof MediaCenterNewsIdRoute
}

const MediaCenterNewsRouteChildren: MediaCenterNewsRouteChildren = {
  MediaCenterNewsIdRoute: MediaCenterNewsIdRoute,
}

const MediaCenterNewsRouteWithChildren = MediaCenterNewsRoute._addFileChildren(
  MediaCenterNewsRouteChildren,
)

interface MediaCenterPhotoGalleryRouteChildren {
  MediaCenterPhotoGalleryIdRoute: typeof MediaCenterPhotoGalleryIdRoute
}

const MediaCenterPhotoGalleryRouteChildren: MediaCenterPhotoGalleryRouteChildren =
  {
    MediaCenterPhotoGalleryIdRoute: MediaCenterPhotoGalleryIdRoute,
  }

const MediaCenterPhotoGalleryRouteWithChildren =
  MediaCenterPhotoGalleryRoute._addFileChildren(
    MediaCenterPhotoGalleryRouteChildren,
  )

interface MediaCenterPressReleasesRouteChildren {
  MediaCenterPressReleasesIdRoute: typeof MediaCenterPressReleasesIdRoute
}

const MediaCenterPressReleasesRouteChildren: MediaCenterPressReleasesRouteChildren =
  {
    MediaCenterPressReleasesIdRoute: MediaCenterPressReleasesIdRoute,
  }

const MediaCenterPressReleasesRouteWithChildren =
  MediaCenterPressReleasesRoute._addFileChildren(
    MediaCenterPressReleasesRouteChildren,
  )

interface MediaCenterVideoGalleryRouteChildren {
  MediaCenterVideoGalleryIdRoute: typeof MediaCenterVideoGalleryIdRoute
}

const MediaCenterVideoGalleryRouteChildren: MediaCenterVideoGalleryRouteChildren =
  {
    MediaCenterVideoGalleryIdRoute: MediaCenterVideoGalleryIdRoute,
  }

const MediaCenterVideoGalleryRouteWithChildren =
  MediaCenterVideoGalleryRoute._addFileChildren(
    MediaCenterVideoGalleryRouteChildren,
  )

interface MediaCenterRouteChildren {
  MediaCenterNewsRoute: typeof MediaCenterNewsRouteWithChildren
  MediaCenterPhotoGalleryRoute: typeof MediaCenterPhotoGalleryRouteWithChildren
  MediaCenterPressReleasesRoute: typeof MediaCenterPressReleasesRouteWithChildren
  MediaCenterVideoGalleryRoute: typeof MediaCenterVideoGalleryRouteWithChildren
  MediaCenterIndexRoute: typeof MediaCenterIndexRoute
}

const MediaCenterRouteChildren: MediaCenterRouteChildren = {
  MediaCenterNewsRoute: MediaCenterNewsRouteWithChildren,
  MediaCenterPhotoGalleryRoute: MediaCenterPhotoGalleryRouteWithChildren,
  MediaCenterPressReleasesRoute: MediaCenterPressReleasesRouteWithChildren,
  MediaCenterVideoGalleryRoute: MediaCenterVideoGalleryRouteWithChildren,
  MediaCenterIndexRoute: MediaCenterIndexRoute,
}

const MediaCenterRouteWithChildren = MediaCenterRoute._addFileChildren(
  MediaCenterRouteChildren,
)

interface OlympiansIdRouteChildren {
  OlympiansIdHighlightsRoute: typeof OlympiansIdHighlightsRoute
  OlympiansIdIndexRoute: typeof OlympiansIdIndexRoute
}

const OlympiansIdRouteChildren: OlympiansIdRouteChildren = {
  OlympiansIdHighlightsRoute: OlympiansIdHighlightsRoute,
  OlympiansIdIndexRoute: OlympiansIdIndexRoute,
}

const OlympiansIdRouteWithChildren = OlympiansIdRoute._addFileChildren(
  OlympiansIdRouteChildren,
)

interface OlympiansRouteChildren {
  OlympiansIdRoute: typeof OlympiansIdRouteWithChildren
  OlympiansIndexRoute: typeof OlympiansIndexRoute
}

const OlympiansRouteChildren: OlympiansRouteChildren = {
  OlympiansIdRoute: OlympiansIdRouteWithChildren,
  OlympiansIndexRoute: OlympiansIndexRoute,
}

const OlympiansRouteWithChildren = OlympiansRoute._addFileChildren(
  OlympiansRouteChildren,
)

interface RegisterRouteChildren {
  RegisterAssociationRoute: typeof RegisterAssociationRoute
  RegisterAthleteCoachRoute: typeof RegisterAthleteCoachRoute
  RegisterDepartmentOfficerRoute: typeof RegisterDepartmentOfficerRoute
  RegisterInstitutionRoute: typeof RegisterInstitutionRoute
  RegisterLocalSelfGovernmentRoute: typeof RegisterLocalSelfGovernmentRoute
  RegisterSportsComplexRoute: typeof RegisterSportsComplexRoute
  RegisterYouthClubRoute: typeof RegisterYouthClubRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterAssociationRoute: RegisterAssociationRoute,
  RegisterAthleteCoachRoute: RegisterAthleteCoachRoute,
  RegisterDepartmentOfficerRoute: RegisterDepartmentOfficerRoute,
  RegisterInstitutionRoute: RegisterInstitutionRoute,
  RegisterLocalSelfGovernmentRoute: RegisterLocalSelfGovernmentRoute,
  RegisterSportsComplexRoute: RegisterSportsComplexRoute,
  RegisterYouthClubRoute: RegisterYouthClubRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface StadiumsArenasRouteChildren {
  StadiumsArenasIdRoute: typeof StadiumsArenasIdRoute
  StadiumsArenasIndexRoute: typeof StadiumsArenasIndexRoute
}

const StadiumsArenasRouteChildren: StadiumsArenasRouteChildren = {
  StadiumsArenasIdRoute: StadiumsArenasIdRoute,
  StadiumsArenasIndexRoute: StadiumsArenasIndexRoute,
}

const StadiumsArenasRouteWithChildren = StadiumsArenasRoute._addFileChildren(
  StadiumsArenasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AwardSchemesRoute: AwardSchemesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DistrictWebsitesRoute: DistrictWebsitesRouteWithChildren,
  EliteAthletesRoute: EliteAthletesRouteWithChildren,
  EventCalendarRoute: EventCalendarRoute,
  HostelSchemesRoute: HostelSchemesRoute,
  InfrastructureMapRoute: InfrastructureMapRoute,
  LeadershipTeamRoute: LeadershipTeamRoute,
  LiveScoresRoute: LiveScoresRoute,
  LoginRoute: LoginRoute,
  MediaCenterRoute: MediaCenterRouteWithChildren,
  NationalGamesRoute: NationalGamesRoute,
  OlympiansRoute: OlympiansRouteWithChildren,
  OrganisationStructureRoute: OrganisationStructureRoute,
  RegisterRoute: RegisterRouteWithChildren,
  ResultsArchiveRoute: ResultsArchiveRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SportsAcademiesRoute: SportsAcademiesRoute,
  SportsComplexesRoute: SportsComplexesRoute,
  StadiumsArenasRoute: StadiumsArenasRouteWithChildren,
  StipendsGrantsRoute: StipendsGrantsRoute,
  VenuesRoute: VenuesRoute,
  NoticesAnnouncementsRoute: NoticesAnnouncementsRoute,
  NoticesETendersRoute: NoticesETendersRoute,
  NoticesPastEventsRoute: NoticesPastEventsRoute,
  NoticesRecruitmentsRoute: NoticesRecruitmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
